/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.awt.event.*;
import java.io.FileWriter;
import javax.swing.JPanel;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author Harry Thorpe
 */
public class TuingUI extends javax.swing.JFrame {

    static ArrayList<String> CommandHistoryList = new ArrayList<String>();
    static int listcount = 0;
    static String CommandHistory = "";
    
    ChartObject charter;
    Serial serial;
    
    /**
     * Creates new form TuingUI
     */
    public TuingUI() {
        initComponents();
        
        lb_console.setText("");
        
        ((DefaultCaret)ta_history.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        ((DefaultCaret)ta_reviced.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        //create chart
        charter = new ChartObject(chartPnlArea);
        charter.start();
        
        //create serial connection
        serial = new Serial(ta_reviced,charter);
        Comms_Label.setText(serial.getCommsPort());
    }
    
          
    public void submit(String command){
        CommandHistory += "["+ CommandHistoryList.size() + "]" + command +"\n";
        CommandHistoryList.add(command);
        listcount = CommandHistoryList.size();
        ta_history.setText(CommandHistory);
        lb_console.setText(command);
        
        serial.sendData(command);

    }
    
    public String getAdress(){
        try{
                int adress = Integer.parseInt(tx_adress.getText());
                return String. format("%02d", adress);
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "Adress is not a number", "Error", JOptionPane.ERROR_MESSAGE);
            }
        return "00";
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Connect_Button = new javax.swing.JButton();
        tx_command = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_history = new javax.swing.JTextArea();
        Send_Button = new javax.swing.JButton();
        Step_Button = new javax.swing.JButton();
        Disconnect_Button = new javax.swing.JButton();
        SetTunings_Button = new javax.swing.JButton();
        kpSlider = new javax.swing.JSlider();
        kdSlider = new javax.swing.JSlider();
        kiSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_console = new javax.swing.JLabel();
        chartPnlArea = new javax.swing.JPanel();
        Comms_Titel_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_reviced = new javax.swing.JTextArea();
        Command_Titel_Label = new javax.swing.JLabel();
        Recived_Titel_Label = new javax.swing.JLabel();
        Comms_Label = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        SetSpeed_Button = new javax.swing.JButton();
        Start_CheckBox = new javax.swing.JCheckBox();
        SpeedSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        currentSpeed = new javax.swing.JTextField();
        currentP = new javax.swing.JTextField();
        currentI = new javax.swing.JTextField();
        currentD = new javax.swing.JTextField();
        Recived_Titel_Label1 = new javax.swing.JLabel();
        saveData_Button = new javax.swing.JButton();
        tx_adress = new javax.swing.JTextField();
        Comms_Titel_Label1 = new javax.swing.JLabel();
        cb_comm = new javax.swing.JComboBox<>();
        Comms_Titel_Label2 = new javax.swing.JLabel();
        tune_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Connect_Button.setText("Connect");
        Connect_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connect_ButtonActionPerformed(evt);
            }
        });

        tx_command.setToolTipText("Enter Command");
        tx_command.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_commandKeyPressed(evt);
            }
        });

        ta_history.setEditable(false);
        ta_history.setColumns(20);
        ta_history.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        ta_history.setRows(5);
        ta_history.setEnabled(false);
        ta_history.setFocusable(false);
        ta_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta_historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta_historyMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(ta_history);

        Send_Button.setText("Send !");
        Send_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_ButtonActionPerformed(evt);
            }
        });

        Step_Button.setText("Step Inpulse");
        Step_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step_ButtonActionPerformed(evt);
            }
        });

        Disconnect_Button.setText("Disconnect");
        Disconnect_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Disconnect_ButtonActionPerformed(evt);
            }
        });

        SetTunings_Button.setText("Send Tunings");
        SetTunings_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetTunings_ButtonActionPerformed(evt);
            }
        });

        kpSlider.setMajorTickSpacing(10);
        kpSlider.setMinorTickSpacing(5);
        kpSlider.setPaintTicks(true);
        kpSlider.setValue(0);
        kpSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        kpSlider.setDoubleBuffered(true);
        kpSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kpSliderStateChanged(evt);
            }
        });

        kdSlider.setMajorTickSpacing(10);
        kdSlider.setMinorTickSpacing(5);
        kdSlider.setPaintTicks(true);
        kdSlider.setValue(0);
        kdSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kdSliderStateChanged(evt);
            }
        });

        kiSlider.setMajorTickSpacing(10);
        kiSlider.setMinorTickSpacing(5);
        kiSlider.setPaintTicks(true);
        kiSlider.setValue(0);
        kiSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kiSliderStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("kP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("kI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("kD");

        lb_console.setText("console");

        chartPnlArea.setLayout(new javax.swing.BoxLayout(chartPnlArea, javax.swing.BoxLayout.LINE_AXIS));

        Comms_Titel_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Comms_Titel_Label.setText("Comms Port:");

        ta_reviced.setColumns(20);
        ta_reviced.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        ta_reviced.setRows(5);
        ta_reviced.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ta_reviced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ta_revicedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ta_revicedMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(ta_reviced);

        Command_Titel_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Command_Titel_Label.setText("Sent Commands");

        Recived_Titel_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Recived_Titel_Label.setText("Recived Commands");

        Comms_Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Comms_Label.setText("port number");

        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });

        SetSpeed_Button.setText("Send speed");
        SetSpeed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetSpeed_ButtonActionPerformed(evt);
            }
        });

        Start_CheckBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Start_CheckBox.setText("Start");
        Start_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_CheckBoxActionPerformed(evt);
            }
        });

        SpeedSlider.setMajorTickSpacing(50);
        SpeedSlider.setMaximum(200);
        SpeedSlider.setMinimum(-200);
        SpeedSlider.setMinorTickSpacing(10);
        SpeedSlider.setPaintTicks(true);
        SpeedSlider.setValue(0);
        SpeedSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        SpeedSlider.setDoubleBuffered(true);
        SpeedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpeedSliderStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("speed");

        currentSpeed.setText("0.0");
        currentSpeed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentSpeedKeyTyped(evt);
            }
        });

        currentP.setText("0.0");
        currentP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentPKeyTyped(evt);
            }
        });

        currentI.setText("0.0");
        currentI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentIKeyTyped(evt);
            }
        });

        currentD.setText("0.0");
        currentD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentDKeyTyped(evt);
            }
        });

        Recived_Titel_Label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Recived_Titel_Label1.setText("Last Command:");

        saveData_Button.setText("Save Data");
        saveData_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveData_ButtonActionPerformed(evt);
            }
        });

        tx_adress.setText("9");
        tx_adress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_adressKeyTyped(evt);
            }
        });

        Comms_Titel_Label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Comms_Titel_Label1.setText("Adress");

        cb_comm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serial", "I2C" }));

        Comms_Titel_Label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Comms_Titel_Label2.setText("Communication");

        tune_button.setText("Tune");
        tune_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tune_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Command_Titel_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel1))
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(kiSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                            .addComponent(kpSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kdSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SpeedSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(currentP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(currentI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(currentD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Recived_Titel_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Recived_Titel_Label1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_console, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx_command, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Comms_Titel_Label))
                                        .addGap(18, 18, 18)
                                        .addComponent(Send_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Disconnect_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Comms_Titel_Label1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Connect_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Comms_Titel_Label2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_comm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(Start_CheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveData_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tune_button)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Step_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SetTunings_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SetSpeed_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Comms_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                .addComponent(chartPnlArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(Connect_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Disconnect_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Comms_Titel_Label2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cb_comm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(tx_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Comms_Titel_Label1))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Step_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SetSpeed_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(SetTunings_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(saveData_Button)
                                            .addComponent(Start_CheckBox)
                                            .addComponent(tune_button))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(kpSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(currentP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kiSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(currentI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(currentD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(kdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(4, 4, 4)
                                        .addComponent(Comms_Titel_Label))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Comms_Label)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tx_command, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Send_Button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Command_Titel_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_console)
                                    .addComponent(Recived_Titel_Label1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Recived_Titel_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chartPnlArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Disconnect_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disconnect_ButtonActionPerformed
        // TODO add your handling code here:
        //Disconnect Serial
        serial.closeConnection();
    }//GEN-LAST:event_Disconnect_ButtonActionPerformed

    private void SetTunings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetTunings_ButtonActionPerformed
        // TODO add your handling code here:
        //Send Tuning values
        try{
                double temp = Double.parseDouble(currentP.getText());
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "KP is not a number", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        try{
                double temp = Double.parseDouble(currentI.getText());
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "KI is not a number", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        try{
            double temp = Double.parseDouble(currentD.getText());
        }
        catch(NumberFormatException ex){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "KD is not a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_kp"+currentP.getText());
        
        submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_ki"+currentI.getText());
        
        submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_kd"+currentD.getText());
        
    }//GEN-LAST:event_SetTunings_ButtonActionPerformed

    private void Send_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_ButtonActionPerformed
        //Serial send command 
        submit(tx_command.getText());
        tx_command.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_Send_ButtonActionPerformed

    private void kpSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kpSliderStateChanged
        currentP.setText(Double.toString((double)kpSlider.getValue()/100));
    }//GEN-LAST:event_kpSliderStateChanged

    private void kiSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kiSliderStateChanged
        // TODO add your handling code here:
        currentI.setText(Double.toString((double)kiSlider.getValue()/100));

    }//GEN-LAST:event_kiSliderStateChanged

    private void kdSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kdSliderStateChanged
        // TODO add your handling code here:
        currentD.setText(Double.toString((double)kdSlider.getValue()/100));

    }//GEN-LAST:event_kdSliderStateChanged

    private void Connect_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connect_ButtonActionPerformed
        // TODO add your handling code here:
        //Connect serial
        serial.openConnection();
        
    }//GEN-LAST:event_Connect_ButtonActionPerformed

    private void Step_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step_ButtonActionPerformed
        // TODO add your handling code here:
        // Send step Inpulse
        submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_stop");
        charter.setPvSpeed(0);
        submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_start");
        Start_CheckBox.setSelected(true);
        try{
            charter.setPvSpeed(Double.parseDouble(currentSpeed.getText()));
            submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_set_speed"+currentSpeed.getText());
        }
        catch(NumberFormatException ex){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Speed is not a number", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_Step_ButtonActionPerformed

    private void tx_commandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_commandKeyPressed
        // TODO add your handling code here:
        //System.out.print(evt.getKeyCode());
        switch (evt.getKeyCode()){
            case 10://enter
                submit(tx_command.getText());
                tx_command.setText("");
                break;
            case 38://up
                if(listcount > 0){
                    listcount--;
                    tx_command.setText(CommandHistoryList.get(listcount));
                }
                break;
            case 40://down
                if(listcount < CommandHistoryList.size()-1){
                    listcount++;
                    tx_command.setText(CommandHistoryList.get(listcount));
                }
                break;
        }
    }//GEN-LAST:event_tx_commandKeyPressed

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        // TODO add your handling code here:
        //System.out.println(jScrollBar1.getValue());
        charter.setScale(jScrollBar1.getValue()+20);
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    private void SetSpeed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetSpeed_ButtonActionPerformed
        // TODO add your handling code here:
        try{
            charter.setPvSpeed(Double.parseDouble(currentSpeed.getText()));
            submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_set_speed"+currentSpeed.getText());
        }
        catch(NumberFormatException ex){
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Speed is not a number", "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_SetSpeed_ButtonActionPerformed

    private void SpeedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpeedSliderStateChanged
        // TODO add your handling code here:
        currentSpeed.setText(Double.toString((double)SpeedSlider.getValue()));
    }//GEN-LAST:event_SpeedSliderStateChanged

    private void currentSpeedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentSpeedKeyTyped
        int in = evt.getKeyChar();
        //System.out.println(in);
        int[] checks = new int[] {8,37,39,45,46,48,49,50,51,52,53,54,55,56,57,127};
        if(!contains(checks, in)){
            evt.consume();
        }
        if(in == 10){
            try{
                SpeedSlider.setValue((int)Double.parseDouble(currentSpeed.getText()));
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "Speed is not a number", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_currentSpeedKeyTyped

    private void currentPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentPKeyTyped
        int in = evt.getKeyChar();
        //System.out.println(in);
        int[] checks = new int[] {8,37,39,46,48,49,50,51,52,53,54,55,56,57,127};
        if(!contains(checks, in)){
            evt.consume();
        }
                if(in == 10){
            try{
                kpSlider.setValue((int)Double.parseDouble(currentP.getText()));
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "KP is not a number", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_currentPKeyTyped

    private void currentIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentIKeyTyped
        int in = evt.getKeyChar();
        //System.out.println(in);
        int[] checks = new int[] {8,37,39,46,48,49,50,51,52,53,54,55,56,57,127};
        if(!contains(checks, in)){
            evt.consume();
        }
                if(in == 10){
            try{
                kiSlider.setValue((int)Double.parseDouble(currentI.getText()));
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "KI is not a number", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_currentIKeyTyped

    private void currentDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentDKeyTyped
        int in = evt.getKeyChar();
        //System.out.println(in);
        int[] checks = new int[] {8,37,39,46,48,49,50,51,52,53,54,55,56,57,127};
        if(!contains(checks, in)){
            evt.consume();
        }
                if(in == 10){
            try{
                kdSlider.setValue((int)Double.parseDouble(currentD.getText()));
            }
            catch(NumberFormatException ex){
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "KD is not a number", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_currentDKeyTyped

    private void Start_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_CheckBoxActionPerformed
        // TODO add your handling code here:
        if(Start_CheckBox.isSelected())submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_start");
        else{
            submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_stop");
            charter.setPvSpeed(0);
        }
    }//GEN-LAST:event_Start_CheckBoxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        serial.closeConnection();
        serial.openConnection();
        serial.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    private void ta_historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_historyMouseEntered
        // TODO add your handling code here:
        ((DefaultCaret)ta_history.getCaret()).setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
    }//GEN-LAST:event_ta_historyMouseEntered

    private void ta_historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_historyMouseExited
        // TODO add your handling code here:
        ((DefaultCaret)ta_history.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }//GEN-LAST:event_ta_historyMouseExited

    private void ta_revicedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_revicedMouseEntered
        // TODO add your handling code here:
        ((DefaultCaret)ta_reviced.getCaret()).setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
    }//GEN-LAST:event_ta_revicedMouseEntered

    private void ta_revicedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_revicedMouseExited
        // TODO add your handling code here:
        ((DefaultCaret)ta_reviced.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }//GEN-LAST:event_ta_revicedMouseExited

    private void saveData_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveData_ButtonActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("data1.txt");
            FileWriter fileWriter = new FileWriter(file);
            double[][] data = charter.getData();
            for(int i = 0; i < data.length; i++){
                fileWriter.write(data[i][0]+","+data[i][1]);  
                fileWriter.write(System.lineSeparator());
            }
            fileWriter.flush();
            fileWriter.close();
        }   
        catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveData_ButtonActionPerformed

    private void tx_adressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_adressKeyTyped
        // TODO add your handling code here:
                int in = evt.getKeyChar();
        //System.out.println(in);
        int[] checks = new int[] {8,49,50,51,52,53,54,55,56,57};
        if(!contains(checks, in) || tx_adress.getText().length()>=2){
            evt.consume();
        }
    }//GEN-LAST:event_tx_adressKeyTyped

    private void tune_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tune_buttonActionPerformed
        // TODO add your handling code here:
        submit((cb_comm.getSelectedItem().toString()=="I2C" ? getAdress() : "")+"vs_tune");
    }//GEN-LAST:event_tune_buttonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TuingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TuingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TuingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TuingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuingUI().setVisible(true);
                
            }
        });
        
    }
    
    public boolean contains(final int[] array, final int key) {
    for (final int i : array) {
        if (i == key) {
            return true;
        }
    }
    return false;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Command_Titel_Label;
    private javax.swing.JLabel Comms_Label;
    private javax.swing.JLabel Comms_Titel_Label;
    private javax.swing.JLabel Comms_Titel_Label1;
    private javax.swing.JLabel Comms_Titel_Label2;
    private javax.swing.JButton Connect_Button;
    private javax.swing.JButton Disconnect_Button;
    private javax.swing.JLabel Recived_Titel_Label;
    private javax.swing.JLabel Recived_Titel_Label1;
    private javax.swing.JButton Send_Button;
    private javax.swing.JButton SetSpeed_Button;
    private javax.swing.JButton SetTunings_Button;
    private javax.swing.JSlider SpeedSlider;
    private javax.swing.JCheckBox Start_CheckBox;
    private javax.swing.JButton Step_Button;
    private javax.swing.JComboBox<String> cb_comm;
    private static javax.swing.JPanel chartPnlArea;
    private javax.swing.JTextField currentD;
    private javax.swing.JTextField currentI;
    private javax.swing.JTextField currentP;
    private javax.swing.JTextField currentSpeed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider kdSlider;
    private javax.swing.JSlider kiSlider;
    private javax.swing.JSlider kpSlider;
    private javax.swing.JLabel lb_console;
    private javax.swing.JButton saveData_Button;
    private javax.swing.JTextArea ta_history;
    private javax.swing.JTextArea ta_reviced;
    private javax.swing.JButton tune_button;
    private javax.swing.JTextField tx_adress;
    private javax.swing.JTextField tx_command;
    // End of variables declaration//GEN-END:variables
}
